### ISSUE TITLE
Location of new action:  register metamodels

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#105]
Don't we want to place this action (like all our other actions) in the eMoflon submenu?  At the moment it is directly on the same level as our eMoflon submenu.  I'm not sure if this was intended or if the location URI used doesn't work as intended...

**Comment by RolandKluge** [comment]
This is actually unintended.
When I tested eMoflon::Core, the menu entry was in the eMoflon submenu.
I have to check this once more.

**Comment by RolandKluge** [comment]
Fixed in eMoflon::Core 1.3.3.
I also found out why the version number was still at 1.3.2: The PR in https://github.com/eMoflon/emoflon-core/ was still open. I now merged it into master without problems (see https://github.com/eMoflon/emoflon-core/commit/38261ccff063e5aecd309ad3e4bb0f06db7f2d5d)
