### ISSUE TITLE
Better default values?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#11]
- could we use ```platform:/resource/...``` as our default URIs instead of the current ```platform:/plugin/...```?  This simplifies things a bit for a most users and advanced users (who want to actually create eclipse plugins) can change this as required.

- could we remove all options in the default moflon.properties file apart from replace gen model?  All other options are very eMoflon (SDM) specific and don't really make sense in a general context.

**Comment by RolandKluge** [comment]
> Could we use platform:/resource/... as our default URIs instead of the current platform:/plugin/...?
Sure, we can do that, but what is the advantage? That we do not need a plugin-to-resource mapping? If we change the default URI layout, we have to be careful with generated code in eMoflon and if we want to reuse the plugins in other contexts.

> Could we remove all options in the default moflon.properties file?
I also thought about this. I also had to push the generated code to avoid bootstrapping eMoflon Core. However, I do not know how we could achieve this without having two properties files (which would be OK from my perspective - we would need to set up a migration routine, though.

**Comment by anthonyanjorin** [comment]
Advantages of platform:/resource:  (i) the genmodel can be opened by clicking and should just work, (ii) dynamic instances and saved models will just work without any further ado, (iii) the URIs used in our xtext editors will match with the actual URIs of the epackages.

These points can all be solved by appropriate configuration, but users (students) with no prior EMF knowledge will have problems with our default settings.

I would prefer taking the easiest settings so novice users have nothing to do and advanced users can create appropriate mappings etc.

Concerning the moflon.properties file:  I meant again the default right?  So what is created in a new project should be completely empty apart from the option of replacing the genmodel or not.

**Comment by RolandKluge** [comment]
> Advantages of platform:/resource

OK, let's try this out. New issue: eMoflon/emoflon-core#14

> moflon.properties file:

OK, so we do not change the metamodel for moflon.properties.xmi files but we simply use the default value for each option so that the resulting XMI file is **textually** empty apart from the genmodel.
New issue: eMoflon/emoflon-core#15
