### ISSUE TITLE
Dead link to PlantUML update site on website

### ISSUE THREAD

**Issue by buergerj** [eMoflon/emoflon-core#116]
The eMoflon website tells
http://files.idi.ntnu.no/publish/plantuml/repository/

as URL for the PlantUML updatesite.
This URL is dead. The correct, current updatesite, according to http://plantuml.com/eclipse is http://hallvard.github.io/plantuml/

**Comment by anthonyanjorin** [comment]
Thanks, I've fixed this now.  Might take sometime for GitHub pages to push the changes.
