### ISSUE TITLE
Get rid of warnings if possible

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#12]
There are currently a few warnings and I'm not sure if they are (un)important.

**Comment by RolandKluge** [comment]
Do you mean compiler warnings in /gen or in the eMoflon Core source code?

**Comment by anthonyanjorin** [comment]
I mean warnings in the source code of projects in the emoflon-core workspace.

**Comment by RolandKluge** [comment]
I do not see any warnings on my branch.
