### ISSUE TITLE
Add a GenModel annotation for documentation in default .ecore

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#31]
We should encourage documentation of metamodels by generating one GenModel annotation in the default .ecore that we place in newly created emf projects.

**Comment by patrickrobrecht** [comment]
@RolandKluge you may have a look at the project `org.emoflon.ibex.common` in [eMoflon IBeX](https://github.com/eMoflon/emoflon-ibex/blob/master/org.emoflon.ibex.common/model/Common.ecore). You'll find the comments from the annotations in the generated Java code.

For implementation compare the guide in https://github.com/eMoflon/emoflon-ibex/issues/223

**Comment by RolandKluge** [comment]
Done.
