### ISSUE TITLE
Typo NoActionCommandHanlder

### ISSUE THREAD

**Issue by bebedizo** [eMoflon/emoflon-core#39]
Is it on purpose that the following Handler is called Hanlder?

https://github.com/eMoflon/emoflon-core/blob/master/org.moflon.core.ui/src/org/moflon/core/ui/handler/NoActionCommandHanlder.java

I found out because of an error I get when trying to work with an Integration project...
(Just saw, that this following error has been brought up in another issue already.)

eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IE
Framework arguments:  -product org.eclipse.epp.package.modeling.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.modeling.product

org.eclipse.ui
Error
Tue Feb 27 17:45:47 CET 2018
Conflicting handlers for org.moflon.ide.ui.commands.MoflonDevtoolsMenuCommand: {org.moflon.core.ui.handler.NoActionCommandHanlder} vs {org.moflon.core.ui.handler.NoActionCommandHanlder}

**Comment by anthonyanjorin** [comment]
Ahh... that's why there are warnings in the workspace! :)
