### ISSUE TITLE
I have four warnings in /org.moflon.core.ui/plugin.xml

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#44]
.. and I don't really know how to fix them.  

Don't you have the warnings too @RolandKluge ?

**Comment by RolandKluge** [comment]
I did not see them because I have eMoflon Tool installed, which appears to provide the missing nature IDs for identifying integration projects etc.

I will remove the corresponding definitions from the plugin.xml files.
