### ISSUE TITLE
Change default URI type for the sake of eMoflon Tool

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-core#67]
It appears that I cannot really prevent (background) updates of eMoflon Core, which has caused eMoflon Tool to break multiple times due to the platform:/resource URI handling.

@anthonyanjorin I'm afraid, we have to switch the default handling to the traditional style.

**Comment by anthonyanjorin** [comment]
No problem - I’ll maintain an ibex branch and make sure I work mainly on master and always merge all updates into the ibex branch.

**Comment by anthonyanjorin** [comment]
I‘ve thought about this and think I’ll introduce an optional extension point.  Any tool integrating emolfon-core can provide an extension that will override the default URI settings if this is desired.  To be on the safe side I’ll keep platform:/plugin as default and override with platform:/resource for IBeX.

**Comment by RolandKluge** [comment]
OK, this makes sense and is a clean solution compared to setting the default URI type in an activator.
