### ISSUE TITLE
EMF project setup: Improve .gitignore, remove unnecessary keep files

### ISSUE THREAD

**Issue by patrickrobrecht** [eMoflon/emoflon-core#68]
- As the `model/*.genmodel` is generated, it should be added to the `.gitignore`.
- As the `model` folder contains a versioned file (the `*.ecore`) no `.keepmodel` is necessary.
- The `gen` folder does not need a `.keepgen` as the build will create the folder if it does not exist (cp. the `injection` folder).

The following `.gitignore` should be fine:
```
/bin/
/gen/
/model/*.genmodel
```

**Comment by RolandKluge** [comment]
Did you also test this when checking out a project freshly?
As far as I can remember, Eclipse complains about missing source folders and stops the build (at least when using eMoflon's autosetup utility).

But yes, you are right. The typical user may not need this.

I will adjust the default file content for .gitignore  during the next maintenance phase.
