### ISSUE TITLE
Improve our PSF import function

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#69]
Our little “cloud” menu to import PSFs is pretty but also quite useless at the moment.  There are no pre-entered values and the standard PSF import in Eclipse is actually better because it can handle URLs, i.e., one doesn’t require the actual PSF file locally.

I propose we do two things:

- accept only URLs to PSF files as opposed to the actual files themselves.  The aim is usually to check out some projects *before* cloning the respective git repositories.

- we should establish an extension point so that other plugins can hook into our menu here and pre-enter some PSF URLs.  Without this extra functionality, our pretty cloud is simply not worth the extra effort of maintaining it.

What do you think @rolandkluge?

**Comment by RolandKluge** [comment]
Useless is a pretty hard word, given that eMoflon Tool already adds the eMoflon-Tool-specific entries. :-)

See here: https://github.com/eMoflon/emoflon-tool/blob/master/org.moflon.testing.autotester/plugin.xml#L21

* I agree that providing URLs (also to local files?) would make sense!
* Currently, we use the Eclipse-provided 'menuContribution' extension point to add new entries in eMoflon Tool (see link above). If we document this extension point properly, would this suffice for your purposes?

**Comment by anthonyanjorin** [comment]
@rolandkluge Right - I‘d forgotten about the eMoflon-tool entries.  I’ll have to experiment a bit and see how much of the required functionality for the commands is already in core.  Providing a new extension point could reduce the required „code“ to just an extension that provides a URL.

**Comment by anthonyanjorin** [comment]
just added a simple extension point that can be used to register PSF URLs.  This is now being used in Ibex to add the handbook PSF URLs.  Seems to be working (as long as GitHub does not timeout).
