### ISSUE TITLE
Unable to set up dev workspace for emoflon-core

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#7]
Please provide a README explaining what is required to setup a development workspace for emoflon-core.

My experiments show that one needs at least to install Xtext.

**Comment by anthonyanjorin** [comment]
One also needs maven for Eclipse I guess:  http://download.eclipse.org/technology/m2e/releases

**Comment by anthonyanjorin** [comment]
Not sure what to install for "tycho".

**Comment by anthonyanjorin** [comment]
Ok - the main problem (after manually executing the .xtext grammar) is that imports of the kind  ```org.gervarro.eclipse.workspace.*``` cannot be resolved.  So I guess there are still some dependencies to other eMoflon projects or plugins that are not in the workspace (or one would have to install).

**Comment by RolandKluge** [comment]
Tycho is purely optional. You do not have to install Maven at all to use eMoflon Core.

But yes, if you want to make sure that CI passes, it makes sense to install m2e.

**Comment by RolandKluge** [comment]
Tycho is purely optional. You do not have to install Maven at all to use eMoflon Core.

But yes, if you want to make sure that CI passes, it makes sense to install m2e.

**Comment by RolandKluge** [comment]
See here for a first README file:
https://github.com/eMoflon/emoflon-core/blob/rkluge-dev/README.md#how-to-set-up-an-emoflon-core-developer-workspace

Does it work for you?

**Comment by anthonyanjorin** [comment]
If you add how to deploy the update site I could try that to (and update+test it after adding something).

**Comment by RolandKluge** [comment]
I have added a note regarding the release process here:
https://github.com/eMoflon/emoflon-core/blob/rkluge-dev/README.md#how-to-set-up-an-emoflon-core-developer-workspace
