### ISSUE TITLE
NewMoflonEmfProjectWizard should respect extension for uri configuration

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#72]
The NewMoflonEmfProjectWizard currently has platform:/resource hard coded as the URI for all new EPackages.  We could now also respect the new extension and use the value provided there for this.

**Comment by RolandKluge** [comment]
How do I use the new extension point? Do you have a pointer for me?

**Comment by anthonyanjorin** [comment]
The usage is encapsulated in MoflonGenBuilder, i.e., the interface is exactly the same as before only that the Builder does not access a preference but checks for registered extensions.

So I don't think you need to worry about it -- just use the same method of MoflonGenBuilder that e.g. the Dependencies use.

**Comment by RolandKluge** [comment]
OK, I will do that.
