### ISSUE TITLE
Consider using an xtend template in NewMoflonEmfProjectWizard

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#73]
The code in NewMoflonEmfProjectWizard creating a new metamodel project could be improved by using an Xtend template to create, e.g., the string required for the default documentation annotation (this is currently done using strings directly).

**Comment by RolandKluge** [comment]
At the point of creating the wizard, I deliberately did not use xtend to keep the implementation simple. I guess we now have several xtend templates so maybe switching back to xtend for this template does not increase the overall complexity that much.
