### ISSUE TITLE
Autotester/PSF import should not try to launch arbitrary projects

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#79]
For some reason, our autotester  / PSF import always tries to "launch" one of the projects.  Shouldn't this only be the case if the naming convention *testsuite* is adhered to?  In the case of the ibex handbook projects this auto launch feature doesn't make much sense and just fails with an ugly error message.

**Comment by RolandKluge** [comment]
A while ago, we switched the convention if I remember correctly. The autotester now searches for launch configs having a certain name.

**Comment by anthonyanjorin** [comment]
aha - hmm...  then I'll have to check what the problem is (and perhaps just avoid the naming convention).
For some reason, the launching doesn't work (even though it should and does after cleaning and building all projects).

**Comment by patrickrobrecht** [comment]
It seems that all .launch files are executed after a PSF import via the eMoflon dialog. I imported the eMoflon::IBeX examples into my test workspace and suddenly Eclipse starts to execute the testsuites for TGGs which are not in any of the imported projects. This cannot be the indended behavior, right?

**Comment by RolandKluge** [comment]
Here is the relevant location in the code:
https://github.com/eMoflon/emoflon-core/blob/master/org.moflon.core.ui.autosetup/src/org/moflon/core/ui/autosetup/ExploreEMoflonProjectsJob.java#L101

**Comment by anthonyanjorin** [comment]
The regular expression wasn't working as it should so I replaced it with a standard check.  The convention (slightly changed) is now that the launch file should end with ".launch" and should contain "TestSuite" in its name.  I think that's ok -- if it's not we can change it easily.
