### ISSUE TITLE
HTTPS for GitHub pages emoflon.org

### ISSUE THREAD

**Issue by patrickrobrecht** [eMoflon/emoflon-core#82]
`https://emoflon.github.io` redirects to `http://emoflon.org` instead of `https://emoflon.org`.

As [GitHub announced support for HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), this can be easily fixed such that the update sites are available over HTTPS.

**Comment by RolandKluge** [comment]
Thanks for reporting. We changed the DNS entry, but still have to wait for the settings to take effect.

**Comment by patrickrobrecht** [comment]
Thank you, it's working! I've adjusted the update site link in the README.
