### ISSUE TITLE
Avoid implementations of BiMap and BiHashMap

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#84]
I doubt if it's a good idea to start our very own implementations of extra collections (BiMap and HashBiMap) in core.  I'm pretty sure Apache or Guava provide an excellent choice of such beefed up collections and much more.

**Comment by RolandKluge** [comment]
Thanks for the hint. I did not known that the code that I migrated from the GT repositories contains such tweaks.
