### ISSUE TITLE
Remove dead code for correspondence model visualisation

### ISSUE THREAD

**Issue by eTralse** [eMoflon/emoflon-core#91]
The code for visualising correspondence models is located in EMoflonMetaModelVisualiser until including commit 9175f4322b01fcc890d6553b85cfc5a0c034fd29 (see [EMoflonModelAndMetamodelVisualiser](https://github.com/eMoflon/emoflon-core/blob/9175f4322b01fcc890d6553b85cfc5a0c034fd29/org.moflon.core.ui/src/org/moflon/core/ui/visualisation/EMoflonModelAndMetamodelVisualiser.java)). Following a refactoring, it is supposed to be removed from the Ecore visualiser. Therefore it needs to be added somewhere else, i.e. to the TGG visualisation.

**Comment by mvdheram** [comment]
I have removed the code for visualising the correspondence models of the tgg file in the EMoflonPlantUMLGenerator.xtend, have compiled and ran a run configuration. THe visualization for correspondence model is generated by plantUML
