### ISSUE TITLE
Replace tutorial for hints on how to install an update site

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#92]
Our current link to a tutorial for people who paste our update site in a normal web browser is broken.  We should replace it (Xtext has a nice link).

**Comment by RolandKluge** [comment]
Can you give me some more context? Which link is it and in how far can XText help here?

**Comment by anthonyanjorin** [comment]
`https://emoflon.org/emoflon-ibex-democles/org.emoflon.ibex.tgg.ide.democles.updatesite/`

I suppose the same tutorial link referenced here is also used for all our other update sites?

This is what Xtext provides instead:

`http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/`

**Comment by RolandKluge** [comment]
For me, both URLs look similar in the browser (apart from the Eclipse logo on the Xtext site).
However, we could think of using the composite update site mechanism to provide a joint update site for all eMoflon artifacts.

**Comment by anthonyanjorin** [comment]
The point was that the tutorial we reference on our landing page is broken.  Xtext references an Eclipse help page, which is probably more stable.

**Comment by RolandKluge** [comment]
I use this link because the link on the XText site does not work properly (just redirects to the help system in general).

https://help.eclipse.org/oxygen/topic/org.eclipse.platform.doc.user/tasks/tasks-124.htm
