### ISSUE TITLE
Somehow give version information of eMoflon with logger?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#93]
I just got a feature request for some kind of version information of eMoflon to be provided programmatically (not only via the normal Eclipse way).  I suppose we could add this to the logger?  Would be nice if this could be automatically updated (extracted from some plugin)?

**Comment by RolandKluge** [comment]
Do you mean something like this?

    Version version = Platform.getBundle("org.eclipse.platform").getVersion();

(https://stackoverflow.com/questions/20653060#20653060)

Do you mean logger in the sense of Log4J? Why and how should we provide the version information via this logger?

I think that the easiest thing would be to store the version info (if necessary at all) in the eMoflon preferences storage.
The easiest way is probably to simply use the framework methods
